---
 - hosts: all
   gather_facts: false

   tasks:
    - name: Enable Root Login
      ansible.builtin.lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: "PermitRootLogin yes"
        state: present
        backup: yes
      become: true
      notify:
        - restart ssh
    
    - name: Create ssh directory
      become: true  
      become_user: root
      ansible.builtin.file:
        path: /root/.ssh
        state: directory
    
    - name: Write authorized_keys
      become: true  
      become_user: root
      ansible.builtin.shell:
        cmd: cat /tmp/id_rsa.pub >>  /root/.ssh/authorized_keys

    - name: hostnamectl set static hostname
      become: true
      become_user: root
      ansible.builtin.shell:
        cmd: hostnamectl set-hostname --static {{ node_name }}

    - name: Preserve Hostname
      become: true
      become_user: root
      ansible.builtin.replace:
        path: /etc/cloud/cloud.cfg
        regexp: 'preserve_hostname: false'
        replace: 'preserve_hostname: true'

    - name: Set FQDN of hostname
      become: true
      become_user: root
      ansible.builtin.replace:
        path: /etc/hosts
        regexp: '127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4'
        replace: '127.0.0.1   {{ node_name }}.kubernetes.local {{ node_name }} localhost4 localhost4.localdomain4'
  
    - name: Copy ca key
      become: true
      become_user: root
      ansible.builtin.copy:
        src: /tmp/ca.key
        dest: ~/ca.key

    # - name: Copy ca cert
    #   become: true
    #   become_user: root
    #   ansible.builtin.copy:
    #     src: /tmp/ca.crt
    #     dest: ~/ca.crt
    
    # - name: Copy api server key
    #   become: true
    #   become_user: root
    #   ansible.builtin.copy:
    #     src: /tmp/kube-api-server.key
    #     dest: ~/kube-api-server.key

    # - name: Copy api server cert
    #   become: true
    #   become_user: root
    #   ansible.builtin.copy:
    #     src: /tmp/kube-api-server.crt
    #     dest: ~/kube-api-server.crt

    - name: Copy service accounts key
      become: true
      become_user: root
      ansible.builtin.copy:
        src: /tmp/service-accounts.key
        dest: ~/service-accounts.key

    - name: Copy service accounts cert
      become: true
      become_user: root
      ansible.builtin.copy:
        src: /tmp/service-accounts.crt
        dest: ~/service-accounts.crt

    - name: Copy populate hosts
      become: true
      become_user: root
      ansible.builtin.copy:
        src: /tmp/populate_hosts.py
        dest: ~/populate_hosts.py

    - name: Copy admin.kubeconfig
      become: true
      become_user: root
      ansible.builtin.copy:
        src: /tmp/admin.kubeconfig
        dest: ~/admin.kubeconfig

    - name: Copy kube-controller-manager.kubeconfig
      become: true
      become_user: root
      ansible.builtin.copy:
        src: /tmp/kube-controller-manager.kubeconfig
        dest: ~/kube-controller-manager.kubeconfig

    - name: Copy kube-scheduler.kubeconfig
      become: true
      become_user: root
      ansible.builtin.copy:
        src: /tmp/kube-scheduler.kubeconfig
        dest: ~/kube-scheduler.kubeconfig

    - name: Copy encryption-config.yaml
      become: true
      become_user: root
      ansible.builtin.copy:
        src: /tmp/encryption-config.yaml
        dest: ~/encryption-config.yaml

    - name: Install ssm agent
      become: true
      become_user: root
      ansible.builtin.shell:
        cmd: sudo dnf install -y https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
      notify:
        - start ssm agent

    - name: Configure etcd
      become: true
      become_user: root
      ansible.builtin.shell: |
        curl -L https://storage.googleapis.com/etcd/{{ etcd_version }}/etcd-{{ etcd_version }}-linux-amd64.tar.gz -o /tmp/etcd-{{ etcd_version }}-linux-amd64.tar.gz
        mkdir /tmp/etcd-{{ etcd_version }}-linux-amd64
        tar xzvf /tmp/etcd-{{ etcd_version }}-linux-amd64.tar.gz -C /tmp/etcd-{{ etcd_version }}-linux-amd64 --strip-components=1
        mv /tmp/etcd-{{ etcd_version }}-linux-amd64/etcd* /usr/bin/
        mkdir -p /etc/etcd /var/lib/etcd
        chmod 700 /var/lib/etcd
        cp /tmp/ca.crt /tmp/kube-api-server.key /tmp/kube-api-server.crt /etc/etcd/
        cd /root
        ausearch -c '(etcd)' --raw | audit2allow -M the-etcd
        semodule -X 300 -i the-etcd.pp
        restorecon -Rv /usr/bin/etcd

    - name: Copy etcd.service
      become: true
      become_user: root
      ansible.builtin.copy:
        src: /tmp/etcd.service
        dest: /etc/systemd/system/
        mode: '644'
      notify:
          - stop etcd

    - name: Copy start_etcd.sh
      become: true
      become_user: root
      ansible.builtin.copy:
        src: /tmp/start_etcd.sh
        dest: ~/start_etcd.sh
        mode: u+rwx

   handlers:
    - name: restart ssh
      become: true
      become_user: root
      ansible.builtin.systemd:
        name: sshd
        state: restarted
    
    - name: start ssm agent
      become: true
      become_user: root
      ansible.builtin.systemd:
        name: amazon-ssm-agent
        state: started

    - name: stop etcd
      become: true
      become_user: root
      ansible.builtin.systemd:
        name: etcd
        state: stopped