---
 - hosts: all
   gather_facts: false

   tasks:
    - name: Enable Root Login
      ansible.builtin.lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: "PermitRootLogin yes"
        state: present
        backup: yes
      become: true
      notify:
        - restart ssh
    
    - name: Create ssh directory
      become: true  
      become_user: root
      ansible.builtin.file:
        path: /root/.ssh
        state: directory
    
    - name: Create ssh directory
      become: true  
      become_user: root
      ansible.builtin.shell:
        cmd: cat /tmp/id_rsa.pub >>  /root/.ssh/authorized_keys

    - name: hostnamectl set static hostname
      become: true
      become_user: root
      ansible.builtin.shell:
        cmd: hostnamectl set-hostname --static {{ node_name }}

    - name: Preserve Hostname
      become: true
      become_user: root
      ansible.builtin.replace:
        path: /etc/cloud/cloud.cfg
        regexp: 'preserve_hostname: false'
        replace: 'preserve_hostname: true'

    - name: Set FQDN of hostname
      become: true
      become_user: root
      ansible.builtin.replace:
        path: /etc/hosts
        regexp: '127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4'
        replace: '127.0.0.1   {{ node_name }}.kubernetes.local {{ node_name }} localhost4 localhost4.localdomain4'
  
    - name: Copy ca key
      become: true
      become_user: root
      ansible.builtin.copy:
        src: /tmp/ca.key
        dest: ~/ca.key

    - name: Copy ca cert
      become: true
      become_user: root
      ansible.builtin.copy:
        src: /tmp/ca.crt
        dest: ~/ca.crt
    
    - name: Copy api server key
      become: true
      become_user: root
      ansible.builtin.copy:
        src: /tmp/kube-api-server.key
        dest: ~/kube-api-server.key

    - name: Copy api server cert
      become: true
      become_user: root
      ansible.builtin.copy:
        src: /tmp/kube-api-server.crt
        dest: ~/kube-api-server.crt

    - name: Copy service accounts key
      become: true
      become_user: root
      ansible.builtin.copy:
        src: /tmp/service-accounts.key
        dest: ~/service-accounts.key

    - name: Copy service accounts cert
      become: true
      become_user: root
      ansible.builtin.copy:
        src: /tmp/service-accounts.crt
        dest: ~/service-accounts.crt

    - name: Copy populate hosts
      become: true
      become_user: root
      ansible.builtin.copy:
        src: /tmp/populate_hosts.py
        dest: ~/populate_hosts.py

   handlers:
    - name: restart ssh
      become: true
      become_user: root
      ansible.builtin.systemd:
        name: sshd
        state: restarted