kind: ENC[AES256_GCM,data:J0hOAHHf4k2Y0wI3INgAWw==,iv:eey1J7NCu7G6BRO8uGh07vSQ6Pa0+vAiNoA1nKcJmfo=,tag:OmmicHtB10yq41vxgCfVZQ==,type:str]
apiVersion: ENC[AES256_GCM,data:hL4=,iv:8nOChivkzDxtdokLmjiqXbi9n6INUQGMfd++X0x+0EY=,tag:4BEhOHot5eM3LfxAJqU72w==,type:str]
resources:
    - resources:
        - ENC[AES256_GCM,data:4dONzbaMAQ==,iv:cwKKfaSr9A5iJzXfJ1ldA8+AcXUfIWe27ezAD9NqqJ8=,tag:gkl6x7LzNhXqJVCYE0KrHg==,type:str]
      providers:
        - aescbc:
            keys:
                - name: ENC[AES256_GCM,data:qeCLew==,iv:zNWyYY3x8ytWppONrlQzSr4gWlp/XsMUrCl8u42OrB8=,tag:stGZ5T0VozuJDDgawK9xgw==,type:str]
                  secret: ENC[AES256_GCM,data:amPkC6mEJmzsVnDRibJPKd3m5yWBJlzNBfUyOZTmAfE55Lb7WYWGtyKoJZo=,iv:HKpiq3d+21/KJwfOCwqtAK42JEa3bzMsyK4BbmUS5b4=,tag:T//xa3vTGGOWtkBlH9AZOw==,type:str]
        - identity: {}
sops:
    kms:
        - arn: arn:aws:kms:eu-west-1:905418442662:key/89781139-bb5a-45ad-b2bd-0f5180b4e989
          created_at: "2024-05-21T15:06:55Z"
          enc: AQICAHgEzDJltAY6WZIS2D9fsKteym+JTMF04j+oKnFG2kLIsQFjvaCJlgi6I/spBHpDv37GAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM+NlWwDGrbUNdMarTAgEQgDsQYE6JjS2aq9NylklUuLWHyEBzfriaHyp9R7Jm6KUJHmSJ4cVk1AkNKSK86ravSqsfytoYGywqyTlFrg==
          aws_profile: ""
        - arn: arn:aws:kms:eu-west-2:905418442662:key/e77f43e3-77bc-449d-a4d9-8448ba7792d1
          created_at: "2024-05-21T15:06:55Z"
          enc: AQICAHjjWkbrmQHvLSBg08V80BNBl8t6ECEyfEpHspy4F5RjmAH5FYJu5TbuGP45Nx4SNLHcAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMFSkGJDOX5A90byL/AgEQgDsEkQ6bS/Df3UjA/b8aGLrdwuVj2YPr/iCeVaj0FuK/th67zrEquBY/qGEBV1aXPXcvGCe32zDomHRk/Q==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-05-21T15:06:55Z"
    mac: ENC[AES256_GCM,data:wWZNnuzEALdx9vkj4rKqpjYGD1Kib7X11loVk46gDFiM90dpeHFamx/fbK2LhpzqaOMZDm6H4+QtNzMIIhgsanOcp4CPVFL+WKEgJscFjUwPsu4NUStBAGKD/rSnPjQQ9X4OPESfNL8L9c6lP44TgNgOMXJURjLz66v0l4q3WRY=,iv:hpNF6VLRUOmOh1sVe4rNQ+Or8Wqt9C6Jp9wxmiDYC0Q=,tag:sR33sO2SdiGtRMfX87FtgQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
