---
 - hosts: all
   gather_facts: false

   tasks:
    - name: Enable Root Login
      ansible.builtin.lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: "PermitRootLogin yes"
        state: present
        backup: yes
      become: true
      notify:
        - restart ssh
    
    - name: Create ssh directory
      become: true  
      become_user: root
      ansible.builtin.file:
        path: /root/.ssh
        state: directory
    
    - name: Create ssh directory
      become: true  
      become_user: root
      ansible.builtin.shell:
        cmd: cat /tmp/id_rsa.pub >>  /root/.ssh/authorized_keys

    - name: hostnamectl set static hostname
      become: true
      become_user: root
      ansible.builtin.shell:
        cmd: hostnamectl set-hostname --static {{ node_name }}

    - name: Preserve Hostname
      become: true
      become_user: root
      ansible.builtin.replace:
        path: /etc/cloud/cloud.cfg
        regexp: 'preserve_hostname: false'
        replace: 'preserve_hostname: true'

    - name: Set FQDN of hostname
      become: true
      become_user: root
      ansible.builtin.replace:
        path: /etc/hosts
        regexp: '127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4'
        replace: '127.0.0.1   {{ node_name }}.kubernetes.local {{ node_name }} localhost4 localhost4.localdomain4'

    - name: Create kubelet directory
      become: true  
      become_user: root
      ansible.builtin.file:
        path: /var/lib/kubelet
        state: directory

    - name: Copy ca cert
      become: true
      become_user: root
      ansible.builtin.copy:
        src: /tmp/ca.crt
        dest: /var/lib/kubelet/ca.crt

    - name: Copy kubelet cert
      become: true
      become_user: root
      ansible.builtin.copy:
        src: /tmp/kubelet.crt
        dest: /var/lib/kubelet/kubelet.crt

    - name: Copy kubelet key
      become: true
      become_user: root
      ansible.builtin.copy:
        src: /tmp/kubelet.key
        dest: /var/lib/kubelet/kubelet.key

    - name: Copy populate hosts
      become: true
      become_user: root
      ansible.builtin.copy:
        src: /tmp/populate_hosts.py
        dest: ~/populate_hosts.py

   handlers:
    - name: restart ssh
      become: true
      become_user: root
      ansible.builtin.systemd:
        name: sshd
        state: restarted