---
 - hosts: all
   gather_facts: false

   tasks:
    - name: Enable Root Login
      ansible.builtin.lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: "PermitRootLogin yes"
        state: present
        backup: yes
      become: true
      notify:
        - restart ssh
    
    - name: Create ssh directory
      become: true  
      become_user: root
      ansible.builtin.file:
        path: /root/.ssh
        state: directory
    
    - name: Create ssh directory
      become: true  
      become_user: root
      ansible.builtin.shell:
        cmd: cat /tmp/id_rsa.pub >>  /root/.ssh/authorized_keys

    - name: Set persistent hostname
      become: true
      become_user: root
      ansible.builtin.replace:
        path: /etc/hosts
        regexp: '127.0.0.1 localhost'
        replace: '127.0.0.1 localhost server.kubernetes.local server'

    - name: Set FQDN of hostname
      become: true
      become_user: root
      ansible.builtin.shell:
        cmd: hostnamectl set-hostname server

    - name: Preserve Hostname
      become: true
      become_user: root
      ansible.builtin.replace:
        path: /etc/cloud/cloud.cfg
        regexp: 'preserve_hostname: false'
        replace: 'preserve_hostname: true'

   handlers:
    - name: restart ssh
      become: true
      become_user: root
      ansible.builtin.service:
        name: ssh
        state: restarted