---
 - hosts: all
   gather_facts: false

   tasks:
   - name: Enable Root Login
     lineinfile:
           dest: /etc/ssh/sshd_config
           regexp: '^PermitRootLogin'
           line: "PermitRootLogin yes"
           state: present
           backup: yes
     become: true
     notify:
       - restart ssh

   handlers:
    - name: restart ssh
      become: true
      become_user: root
      service:
        name: ssh
        state: restarted