kind: ENC[AES256_GCM,data:crMwaQVlH44ZIA+qjBDRZA==,iv:KCuDAMc2ZEnHu9MsALDBq4K4jyIuJ4ikxORUmxFNO+c=,tag:DfwEOgLv6DK2miYRmcqtJg==,type:str]
apiVersion: ENC[AES256_GCM,data:8Uk=,iv:GEv9IVtXD8Fg8uSbgCzjqpRLBVujzGUgnYeDsVc9RgU=,tag:8kjYV2YwOqzesb4spvvZgQ==,type:str]
resources:
    - resources:
        - ENC[AES256_GCM,data:5KLkeDzruA==,iv:rkaIqSx1i4Zo5jZfOztoI9LoKVSmguqOmgYcAJznoGo=,tag:L8kJcT8UpP2lVPc8Y1hi8Q==,type:str]
      providers:
        - aescbc:
            keys:
                - name: ENC[AES256_GCM,data:E0yYtA==,iv:oZf8q1mhLbVLCxWh6kBNIwfynWyMxjnOmFGmaNn3NkE=,tag:KA+OKjQmRd8scW1DbUMPjQ==,type:str]
                  secret: ENC[AES256_GCM,data:w7O4XWqxV2FXcJu9aM+eNP4gJNxsVS4FxyhN8z4cHMUGgJ8EmQxnuPC3grk=,iv:T+yNO3bI9+oaMuroSySt0W6Hy0tTUH4i8LTaTg6HTSw=,tag:C9hL2wB5Mvz94OBdeC6IYA==,type:str]
        - identity: {}
sops:
    kms:
        - arn: arn:aws:kms:eu-west-1:905418442662:key/89781139-bb5a-45ad-b2bd-0f5180b4e989
          created_at: "2024-05-29T11:50:01Z"
          enc: AQICAHgEzDJltAY6WZIS2D9fsKteym+JTMF04j+oKnFG2kLIsQETNEuTPfG8ZeWtYQtoBD/MAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMW/jcRsGT8KLEvSc1AgEQgDuigN6Z97vVzaA+9oxdC5E7tCgL7Pu+Nir6ItyX/cySeGlBBpahORowQEkAHr9kjfOd7ownxCgrLscrGA==
          aws_profile: ""
        - arn: arn:aws:kms:eu-west-2:905418442662:key/e77f43e3-77bc-449d-a4d9-8448ba7792d1
          created_at: "2024-05-29T11:50:01Z"
          enc: AQICAHjjWkbrmQHvLSBg08V80BNBl8t6ECEyfEpHspy4F5RjmAGHnao6zn7SOD6WzwTHA3A8AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM8QibC7jsPMXwyj/JAgEQgDtFxQwD5Y/1PWzozb6mcpQOT/iuDi6HHd7kLZohFEnNg0azwtgRBxF2uufyq2MWn/T6GcCdlrdRfJYkww==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-05-29T11:50:01Z"
    mac: ENC[AES256_GCM,data:emvV8SfEwaBZTaZeGymLTNmYQ99BpG9R3Nn59dYk0yQzYxFJcDkuqXn51W+wIoMbR2kkc/r5HCTgNp9JGCDqqmb2xaG8C3EYj6pNz9+tnT9B06CgK/zMLXLorwHRfRopl/X/42QtJjKba0rVjocDBld/0wsxh9dgYacKzm5/19c=,iv:PCKd56h+mW38JFUnrLr69Z9wQdkpn8PPAaQOdZyGbP4=,tag:syWvYrkDqgPMPxn7EWdQ9A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
